version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:${TAG}
    environment:
      - "discovery.type=single-node"
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:${TAG}
    ports:
      - "127.0.0.1:5959:5959"
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:${TAG}
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch

volumes:
  data:
    driver: local
